//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Rc4Ciper : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Rc4Ciper(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Rc4Ciper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Rc4Ciper() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DeviceCiperSDKPINVOKE.delete_Rc4Ciper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Rc4Ciper() : this(DeviceCiperSDKPINVOKE.new_Rc4Ciper(), true) {
  }

  public string Encrypt(string pszText, int itxtLength) {
    string ret = DeviceCiperSDKPINVOKE.Rc4Ciper_Encrypt(swigCPtr, pszText, itxtLength);
    return ret;
  }

  public string Decrypt(string pszText, int itxtLength) {
    string ret = DeviceCiperSDKPINVOKE.Rc4Ciper_Decrypt(swigCPtr, pszText, itxtLength);
    return ret;
  }

}
